services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: vota-ai-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: votaai
      POSTGRES_PASSWORD: votaai123
      POSTGRES_DB: vota_ai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U votaai -d vota_ai_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend da aplicação
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vota-ai-backend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://votaai:votaai123@postgres:5432/vota_ai_db
      PORT: 3000
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
