version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sue
      POSTGRES_PASSWORD: suepass
      POSTGRES_DB: sue_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://sue:suepass@postgres:5432/sue_db
      SERVICE_URL: http://backend:3000
      CLOUD_SERVICE_URL: https://backend.vota-ai.com
    depends_on:
      - postgres

volumes:
  pgdata:
